### ISSUE TITLE
/usr/include/c++/6/type_traits errors when installing Caffe

### ISSUE THREAD

**Issue by anselmoferreira** [BVLC/caffe#5123]
I am using CUDA 8.0 on Ubuntu 16.10 and I am trying to install caffe using [this tutorial for 16.04](https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide). I am with several errors when I do the make all command. Most of them are related to type_traits, as you can see below :

 nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h(436): error: identifier "nullptr" is undefined

/usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h(436): error: expected a ";"

/usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h(205): error: expected a ";"

/usr/include/c++/6/exception(63): error: expected a ";"

/usr/include/c++/6/exception(69): error: expected a ";"

/usr/include/c++/6/exception(77): error: expected a ";"

/usr/include/c++/6/exception(85): error: expected a ";"

/usr/include/c++/6/exception(95): error: expected a "{"

/usr/include/c++/6/bits/exception_ptr.h(64): error: function "std::current_exception" returns incomplete type "std::__exception_ptr::exception_ptr"

/usr/include/c++/6/bits/exception_ptr.h(64): error: expected a "{"

/usr/include/c++/6/bits/exception_ptr.h(71): error: namespace "std" has no member "rethrow_exception"

/usr/include/c++/6/bits/exception_ptr.h(81): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(83): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(84): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(86): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(88): error: declaration is incompatible with previous "std::current_exception"
(64): here

/usr/include/c++/6/bits/exception_ptr.h(88): error: use of a local type to declare a function

/usr/include/c++/6/bits/exception_ptr.h(88): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(89): error: use of a local type to declare a function

/usr/include/c++/6/bits/exception_ptr.h(92): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(94): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(97): error: incomplete type is not allowed

/usr/include/c++/6/bits/exception_ptr.h(97): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(118): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(128): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(145): error: use of a local type to declare a function

/usr/include/c++/6/bits/exception_ptr.h(146): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(149): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(154): error: use of a local type to declare a function

/usr/include/c++/6/bits/exception_ptr.h(155): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(158): error: use of a local type to declare a function

/usr/include/c++/6/bits/exception_ptr.h(159): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(162): error: use of a local type to declare a function

/usr/include/c++/6/bits/exception_ptr.h(163): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(171): error: expected a ";"

/usr/include/c++/6/bits/exception_ptr.h(197): error: expected a ";"

/usr/include/c++/6/bits/move.h(47): error: expected a ";"

/usr/include/c++/6/type_traits(71): error: identifier "constexpr" is undefined

/usr/include/c++/6/type_traits(71): error: template parameter "_Tp" may not be redeclared in this scope

/usr/include/c++/6/type_traits(71): error: expected a ";"

/usr/include/c++/6/type_traits(72): error: member "std::integral_constant<_Tp, __v>::_Tp" is not a type name

/usr/include/c++/6/type_traits(73): error: member "std::integral_constant<_Tp, __v>::_Tp" is not a type name

/usr/include/c++/6/type_traits(74): error: identifier "constexpr" is undefined

/usr/include/c++/6/type_traits(79): error: identifier "constexpr" is undefined

/usr/include/c++/6/type_traits(79): error: "value_type" has already been declared in the current scope

/usr/include/c++/6/type_traits(79): error: expected a ";"

/usr/include/c++/6/type_traits(84): error: identifier "constexpr" is undefined

/usr/include/c++/6/type_traits(84): error: "_Tp" is not a function or static data member

/usr/include/c++/6/type_traits(93): error: expected a declaration

/usr/include/c++/6/type_traits(93): error: expected a ";"

/usr/include/c++/6/type_traits(126): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

/usr/include/c++/6/type_traits(242): error: identifier "char16_t" is undefined

/usr/include/c++/6/type_traits(246): error: identifier "char32_t" is undefined

/usr/include/c++/6/type_traits(246): error: class "std::__is_integral_helper<<error-type>>" has already been defined

/usr/include/c++/6/type_traits(344): error: identifier "__float128" is undefined

/usr/include/c++/6/type_traits(460): error: expected a ">"

/usr/include/c++/6/type_traits(464): error: expected a ">"

/usr/include/c++/6/type_traits(472): error: expected a ">"

/usr/include/c++/6/type_traits(476): error: expected a ">"

/usr/include/c++/6/type_traits(484): error: expected a ">"

/usr/include/c++/6/type_traits(488): error: expected a ">"

/usr/include/c++/6/type_traits(496): error: expected a ">"

/usr/include/c++/6/type_traits(500): error: expected a ">"

/usr/include/c++/6/type_traits(508): error: expected a ">"

/usr/include/c++/6/type_traits(512): error: expected a ">"

/usr/include/c++/6/type_traits(520): error: expected a ">"

/usr/include/c++/6/type_traits(524): error: expected a ">"

/usr/include/c++/6/type_traits(532): error: expected a ">"

/usr/include/c++/6/type_traits(536): error: expected a ">"

/usr/include/c++/6/type_traits(544): error: expected a ">"

/usr/include/c++/6/type_traits(548): error: expected a ">"

/usr/include/c++/6/type_traits(558): error: namespace "std" has no member "nullptr_t"

/usr/include/c++/6/type_traits(579): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

/usr/include/c++/6/type_traits(585): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

/usr/include/c++/6/type_traits(592): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

/usr/include/c++/6/type_traits(599): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

/usr/include/c++/6/type_traits(609): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

/usr/include/c++/6/type_traits(635): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

/usr/include/c++/6/type_traits(745): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

/usr/include/c++/6/type_traits(759): error: expected a ";"

/usr/include/c++/6/type_traits(774): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

/usr/include/c++/6/type_traits(784): error: expected a ")"

/usr/include/c++/6/type_traits(795): error: an explicit template argument list is not allowed on this declaration

/usr/include/c++/6/type_traits(795): error: expected a type specifier

/usr/include/c++/6/type_traits(795): error: function returning function is not allowed

/usr/include/c++/6/type_traits(795): error: expected a ";"

/usr/include/c++/6/type_traits(801): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

I really dont know what is happening and even downgraded my GCC to 4.4, but the error persists. What am I doing wrong? Is the problem my 16.10 Ubuntu?

**Comment by PeiyangShi** [comment]
hi,I was encountered with the same problem, did you solve it? :(

**Comment by NasrinJaleel93** [comment]
I am facing the same issue. Did you guys find a solution?

**Comment by PeiyangShi** [comment]
@NasrinJaleel93 actually, after I switched my ubuntu from 16.10 to 16.04, the problem is solved. : )

**Comment by Milaine** [comment]
I have encountered the same issue aswell and I do not want to downgrade but rather fix the issue

**Comment by ruapotato** [comment]
Same issue on OpenSuse TW.
```
# make all
NVCC src/caffe/layers/batch_norm_layer.cu
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/lib64/gcc/x86_64-suse-linux/6/include/stddef.h(436): error: identifier "nullptr" is undefined

/usr/lib64/gcc/x86_64-suse-linux/6/include/stddef.h(436): error: expected a ";"]]
...```

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by JazzTheSaver** [comment]
Mine Ubuntu version is 16.04,too...but still have this problem :(
